[package]
name = "operator"
version = "0.1.0"
edition = "2021"


[dependencies]
kube = { version = "1.1.0", features = ["runtime", "derive", "admission", "rustls-tls", "ws", "socks5", "runtime"] }
kube-runtime = "1.1.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread", "full"] }

thiserror = "2.0.12"
tracing = "0.1.41"
k8s-openapi = { version = "0.25.0", features = ["latest", "schemars"] }
schemars = "0.8"

futures = "0.3.31"
anyhow = "1.0.98"
kube-derive = "1.1.0"
mimalloc = "0.1.47"
tracing-subscriber = { version = "0.3", features = ["registry", "fmt", "env-filter"] }
opentelemetry = { version = "0.30.0", features = ["metrics", "trace", "logs"] }
opentelemetry_sdk = "0.30.0"
opentelemetry-otlp = { version = "0.30.0", features = ["grpc-tonic", "metrics", "logs"] }
opentelemetry-appender-tracing = "0.30.0"
prometheus = "0.13.4"
hyper = { version = "1.6.0", features = ["full"] }
sysinfo = "0.37.0"
http-body-util = "0.1.3"
bytes = "1.10.1"
hyper-util = "0.1.16"


[target.'cfg(target_arch = "x86_64")']
rustflags = ["-C", "target-cpu=native", "-C", "target-feature=+avx2,+fma"]
