[package]
name = "operator"
version.workspace = true
edition.workspace = true

[dependencies]
kube.workspace = true
kube-runtime.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
thiserror.workspace = true
tracing.workspace = true
k8s-openapi.workspace = true
schemars.workspace = true
tracing-subscriber.workspace = true
futures.workspace = true
anyhow.workspace = true
mimalloc.workspace = true

[target.'cfg(target_arch = "x86_64")']
rustflags = ["-C", "target-cpu=native", "-C", "target-feature=+avx2,+fma"]
