services:
  moodle-init:
    build: &moodle_build
      context: ./.docker/moodle-nginx
      dockerfile: Dockerfile
      args:
        MOODLE_BUILD_URL: https://download.moodle.org/download.php/direct/stable500/moodle-latest-500.tgz
    image: moodle-plugin-moodle-nginx:local
    deploy: &moodle_deploy
      resources:
        limits:
          cpus: "1"
          memory: 1G
    environment: &moodle_environment
      MOODLE_LANGUAGE: en
      SITE_URL: http://localhost:8080
      MOODLE_SITENAME: "GIS Tests"
      MOODLE_SITESUMMARY: "GIS Tests local Moodle"
      MOODLE_USERNAME: adorsys-gis
      MOODLE_PASSWORD: adorsys-gis-password
      MOODLE_EMAIL: admin@adorsys-gis.local
      DB_TYPE: mariadb
      DB_HOST: mariadb
      DB_HOST_PORT: 3306
      DB_NAME: gis-moodle
      DB_USER: adorsys-gis
      DB_PASS: ""
      DB_PREFIX: mdl_
      SMTP_HOST: maildev
      SMTP_PORT: 1025
      SMTP_USER: ""
      SMTP_PASSWORD: ""
      SMTP_PROTOCOL: ""
      MOODLE_MAIL_NOREPLY_ADDRESS: admin@adorsys-gis.local
      MOODLE_MAIL_PREFIX: "[GIS Tests] "
      REDIS_SESSION_ID_HOST: redis
      REDIS_SESSION_ID_PORT: 6379
      REDIS_SESSION_ID_AUTH_STRING: ""
      REDIS_SESSION_IP_AND_PORT: redis:6379
      REDIS_SESSION_AUTH_STRING: ""
      REDIS_APP_IP_AND_PORT: redis:6379
      REDIS_APP_AUTH_STRING: ""
      REDIS_LOCK_HOST_AND_PORT: redis:6379
      REDIS_LOCK_AUTH_STRING: ""
      ENABLE_FRESHCLAM: "no"
      ENABLE_MOOSH_BOOTSTRAP: "no"
    entrypoint:
      - /opt/setup_moodle.sh
    volumes:
      - moodledata_data:/moodleroot-instance1/moodledata
    depends_on: &moodle_depends_on
      mariadb:
        condition: service_started
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
      plugin-downloader:
        condition: service_completed_successfully

  moodle:
    build: *moodle_build
    image: moodle-plugin-moodle-nginx:local
    deploy: *moodle_deploy
    ports:
      - "8080:8080"
    environment: *moodle_environment
    volumes:
      - moodledata_data:/moodleroot-instance1/moodledata
      - ./plugins/ai/provider/openaicompatible:/moodleroot-instance1/moodle/ai/provider/openaicompatible:ro
      - ./plugins/gis-theme/adorsys_theme_v1:/moodleroot-instance1/moodle/theme/adorsys_theme_v1:ro
      - plugins_downloads:/moodleroot-instance1/moodle/plugins/downloaded:ro
    depends_on:
      <<: *moodle_depends_on
      moodle-init:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 5s
      retries: 5

  plugin-downloader:
    image: alpine/git:latest
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 128M
    volumes:
      - plugins_downloads:/plugin_downloads
      - ./.docker/plugin-downloader/download_plugin.sh:/scripts/download_plugins.sh:ro
    environment:
      PLUGINS_DIR: "/plugin_downloads"
      PLUGINS_TO_DOWNLOAD: >
        https://moodle.org/plugins/download.php/36782/theme_seo_moodle50_2025070900.zip,theme_seo;
        https://moodle.org/plugins/download.php/36820/mod_minilesson_moodle50_2025071300.zip,mod_minilesson;
        https://moodle.org/plugins/download.php/36766/theme_boost_union_moodle50_2025041414.zip,theme_boost_union;
        https://moodle.org/plugins/download.php/36807/mod_pdfannotator_moodle50_2025071100.zip,mod_pdfannotator
    entrypoint: /bin/sh
    command:
      - "/scripts/download_plugins.sh"

  mariadb:
    image: docker.io/bitnamilegacy/mariadb:latest
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    environment:
      ALLOW_EMPTY_PASSWORD: yes
      MARIADB_USER: adorsys-gis
      MARIADB_DATABASE: gis-moodle
      MARIADB_CHARACTER_SET: utf8mb4
      MARIADB_COLLATE: utf8mb4_unicode_ci
      BITNAMI_DEBUG: true
    volumes:
      - mariadb_data:/bitnami/mariadb

  redis:
    image: docker.io/bitnamilegacy/redis:8.0
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 256M
    environment:
      ALLOW_EMPTY_PASSWORD: yes
      REDIS_EXTRA_FLAGS: --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/bitnami/redis/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 15s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 128M
    ports:
      - "18080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
      ADMINER_DEFAULT_USERNAME: adorsys-gis
      ADMINER_DESIGN: dracula
      ADMINER_PLUGINS: tables-filter tinymce
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080"]
      interval: 30s
      timeout: 5s
      retries: 3

  minio:
    image: docker.io/bitnamilegacy/minio:latest
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    ports:
      - "19000:9000"
    environment:
      MINIO_ROOT_USER: minio-gis
      MINIO_ROOT_PASSWORD: kwak-kwak
    volumes:
      - minio_data:/bitnami/minio/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 5

  minio-object-browser:
    image: docker.io/bitnamilegacy/minio-object-browser:latest
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 125M
    ports:
      - "19090:9090"
    environment:
      CONSOLE_PBKDF_PASSPHRASE: some-passphrase
      CONSOLE_PBKDF_SALT: some-salt
      CONSOLE_MINIO_SERVER: "http://minio:9000"
    command:
      - server

  minio-init:
    image: docker.io/bitnamilegacy/minio-client:latest
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 256M
    volumes:
      - .docker/minio/policy.json:/tmp/policy.json
    command:
      - /bin/bash
      - -c
      - |-
        set -e;
        mc alias set bucketer http://minio:9000 minio-gis kwak-kwak;
        mc mb bucketer/moodle --ignore-existing
        mc anonymous set-json /tmp/policy.json bucketer/moodle
    depends_on:
      minio:
        condition: service_healthy

  maildev:
    image: maildev/maildev
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 128M
    ports:
      - "1080:1080"
      - "1025:1025"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:1080"]
      interval: 30s
      timeout: 5s
      retries: 3

  fileserver:
    image: halverneus/static-file-server
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "18081:8080"
    environment:
      CORS: true
      HOST: 0.0.0.0
    volumes:
      - ./plugins:/web/plugins:ro
      - moodledata_data:/web/moodledata_data
      - plugins_downloads:/web/plugins_downloads
      - mariadb_data:/web/mariadb_data
      - redis_data:/web/redis_data
      - minio_data:/web/minio_data

volumes:
  moodledata_data:
  plugins_downloads:
  mariadb_data:
  redis_data:
  minio_data:
