version: '3.8'

services:
  moodle:
    image: moodlehq/moodle-php-apache:8.1
    ports:
      - "8080:80"
    depends_on:
      - postgres
      - redis
    environment:
      - MOODLE_DB_TYPE=pgsql
      - MOODLE_DB_HOST=postgres
      - MOODLE_DB_PORT=5432
      - MOODLE_DB_USER=moodle
      - MOODLE_DB_PASS=moodle
      - MOODLE_DB_NAME=moodle
      - MOODLE_WWWROOT=http://localhost:8080
      - MOODLE_DATA=/var/www/moodledata
    volumes:
      - moodledata:/var/www/moodledata

  postgres:
    image: ghcr.io/cloudnative-pg/postgresql:14.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=moodle
      - POSTGRES_PASSWORD=moodle
      - POSTGRES_DB=moodle
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:RELEASE.2023-09-07T02-05-02Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - miniodata:/data

volumes:
  moodledata:
  pgdata:
  miniodata: