global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'moodle-operator'
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'localhost:9090'
          - 'host.docker.internal:9090'