apiVersion: v2
name: moodle-operator
description: >
  Helm chart for the Moodle Kubernetes Operator. It installs the Moodle CRD(s)
  and deploys the controller that manages Moodle instances via custom resources.
  Application dependencies (databases, caches, storage) are intentionally not
  bundled—compose them via separate charts. Uses the 'common' library for
  shared helpers and best practices.
type: application
version: 0.2.0              # bump from 0.1.0 since we’re changing deps/behavior
appVersion: "1.16.0"        # keep your current operator image version/tag

keywords:
  - moodle
  - lms
  - operator
  - kubernetes
  - helm

maintainers:
  - name: Stephane Segning
    email: selastlambou@gmail.com
  - name: Adorsys GIS
    email: gis-udm@adorsys.com

dependencies:
  - name: common
    version: 2.31.3
    repository: https://charts.bitnami.com/bitnami
