# Default values for moodle-operator chart
global:
  nameOverride: ""
  fullnameOverride: ""

operator:
  defaultPodOptionsStrategy: overwrite

  controllers:
    main:
      enabled: true
      type: deployment  # Explicitly set the controller type
      strategy: Recreate
      pod:
        securityContext:
          fsGroup: 65534
          runAsGroup: 65534
          runAsNonRoot: true
          runAsUser: 65534
      containers:
        main:
          image:
            repository: moodle-operator
            tag: "1.16.0"
            pullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:  # Container-specific security context
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
            capabilities:
              drop:
                - ALL
      serviceAccount:
        identifier: default

  service:
    main:
      controller: main
      ports:
        http:
          port: 8080

  serviceAccount:
    default:
      enabled: true
      annotations: {}

  rbac:
    roles:
      operator:
        type: ClusterRole
        rules:
          - apiGroups: [""]
            resources: ["pods", "services", "endpoints", "persistentvolumeclaims", "events", "configmaps", "secrets"]
            verbs: ["*"]
          - apiGroups: ["apps"]
            resources: ["deployments", "daemonsets", "replicasets", "statefulsets"]
            verbs: ["*"]
          - apiGroups: ["moodle.adorsys.com"]
            resources: ["*"]
            verbs: ["*"]
    bindings:
      operator:
        type: ClusterRoleBinding
        roleRef:
          identifier: operator
        subjects:
          - identifier: default
