apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: moodles.adorsys-gis-moodle.com
spec:
  group: adorsys-gis-moodle.com
  names:
    kind: Moodle
    plural: moodles
    singular: moodle
    shortNames:
      - mdl
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: Custom resource definition for managing Moodle deployments
          properties:
            spec:
              type: object
              description: Desired configuration for Moodle
              properties:
                moodleUsername:
                  type: string
                  description: Username for the Moodle admin user
                moodlePassword:
                  type: string
                  description: Password for the Moodle admin user
                moodleEmail:
                  type: string
                  description: Email for the Moodle admin user
                replicas:
                  type: integer
                  description: Number of Moodle pods to run
                  default: 1
            status:
              type: object
              description: Current status of the Moodle instance
              properties:
                phase:
                  type: string
                  description: Current phase (e.g., Pending, Running, Failed)
                url:
                  type: string
                  description: Exposed Moodle URL
