apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: moodle-postgresql
  namespace: moodle  
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:15

  bootstrap:
    initdb:
      database: moodledb  
      owner: moodle       
      secret:
        name: moodle-db-secret

  # enableSuperuserAccess: true
  superuserSecret:
    name: moodle-db-secret  
  storage:
    storageClass: local-path
    size: 1Gi
