apiVersion: v2
name: moodle
description: |
  Moodle is a free, open-source learning platform, also known as a Learning Management System (LMS), 
  designed to help educators create and manage online courses and learning environments. 
  This Helm chart deploys Moodle on Kubernetes, providing a scalable and flexible way to run 
  Moodle in a cloud-native infrastructure.

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"

keywords:
  - moodle
  - lms

maintainers:
  - name: Stephane Segning
    email: selastlambou@gmail.com
  - name: Adorsys GIS
    email: gis-udm@adorsys.com

dependencies:
  - name: common
    version: 2.31.3
    repository: https://charts.bitnami.com/bitnami
  - name: moodle
    version: 27.0.3
    repository: https://charts.bitnami.com/bitnami