moodle:
  moodleUsername: admin
  moodlePassword: adorsys-gis
  moodleEmail: gis-udm@adorsys.com

  service:
    type: LoadBalancer

  persistence:
    enabled: true
    size: 10Gi

  mariadb:
    enabled: true
  externalDatabase:
    type: pgsql
    host: my-moodle-postgresql
    port: 5432
    user: bn_moodle_adorsys
    password: moodlepass
    database: moodledb

postgresql:
  enabled: false