moodle:
  moodleUsername: admin
  moodlePassword: adorsys-gis
  moodleEmail: gis-udm@adorsys.com

  service:
    type: LoadBalancer

  mariadb:
    enabled: true

  postgresql:
    enabled: false

  persistence:
    enabled: true
    size: 10Gi

  externalDatabase:
    host: moodle-postgresql-rw
    user: moodle
    password: moodlepass
    database: moodledb

cloudnative-pg:
  enabled: false
  fullnameOverride: moodle-postgresql
