postgresql: 
  enabled: false 
  auth:
      postgresPassword: rootPass
      username: bn_moodle_adorsys
      password: moodlepass
      database: moodledb
  persistence:
    enabled: true
    storageClass: local-path