moodle:
  debug: true
  image:
    registry: docker.io
    repository: bitnamilegacy/moodle
    tag: 5.0.2-debian-12-r2
    pullPolicy: IfNotPresent
  moodleUsername: admin
  moodlePassword: adorsys-gis
  moodleEmail: gis-udm@adorsys.com
  service:
    type: LoadBalancer
  mariadb:
    enabled: false
  persistence:
    enabled: true
    existingClaim: "" #create an external PVC and set this to its name
    size: 10Gi
  externalDatabase:
    enabled: false
postgresql:
  enabled: false    
cnpg:
  enabled: false
