moodle:
  moodleUsername: admin
  moodlePassword: adorsys-gis
  moodleEmail: gis-udm@adorsys.com

  service:
    type: LoadBalancer
    ports:
      http: 80
      https: 443
    targetPorts:
      http: 8080
      https: 8443
      
  persistence:
    enabled: true
    size: 10Gi

  mariadb:
    enabled: false
  externalDatabase:
    type: pgsql
    host: my-moodle-postgresql
    port: 5432
    user: bn_moodle_adorsys
    password: moodlepass
    database: moodledb

postgresql:
  enabled: false