moodle:
  moodleUsername: admin
  moodlePassword: adorsys-gis
  moodleEmail: gis-udm@adorsys.com

  service:
    type: LoadBalancer

  mariadb:
    enabled: false

  persistence:
    enabled: true
    size: 10Gi

postgresql:
  enabled: false
  auth:
    username: moodle
    password: moodlepassword
    database: bitnamimoodle
  primary:
    persistence:
      enabled: false  # Disable PVC for local test clusters

