moodle:
   externalDatabase:
    host: moodle-postgresql-rw
    user: moodle
    type: pgsql
    host: my-moodle-postgresql
    port: 5432
    user: bn_moodle_adorsys
    password: moodlepass
    database: moodledb
postgresql: 
  enabled: true
  image:
    registry: docker.io
    repository: bitnamilegacy/postgresql
    tag: 15.2.0-debian-12-r0
    pullPolicy: IfNotPresent
  auth:
    postgresPassword: rootPass
    username: bn_moodle_adorsys
    password: moodlepass
    database: moodledb
  persistence:
    enabled: true
    storageClass: local-path
 