[package]
name = "ai-core"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.64"
serde_json = "1.0.128"
serde_yaml = "0.9.34"
ai_utils = { path = "../utils" }
anyhow = "1.0.89"
tracing = "0.1.41"
md5 = "0.8.0"
tempfile = "3.20.0"
lru = "0.12.4"  # LRU cache

# Optional for channel/async conversions
tokio = { version = "1.40.0", features = ["rt", "fs"], optional = true }
crossbeam-channel = { version = "0.5.13", optional = true }

[features]
default = []
backtrace = []
tokio = ["dep:tokio", "tokio/rt", "tokio/fs", "tokio/macros"]
crossbeam = ["dep:crossbeam-channel"]