name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Rust operator
      run: |
        cd operators/moodle-operator
        cargo build --verbose

    - name: Build Docker images
      run: |
        docker-compose build