name: CI

on:
  push:
    branches:
      - adorsys-theme-v1
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
         
      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        with: 
          path: |
            ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('plugins/gis-theme/adorsys_theme_v1/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: |
          cd plugins/gis-theme/adorsys_theme_v1
          yarn install --frozen-lockfile
      - name: Build theme assets
        run: |
          cd plugins/gis-theme/adorsys_theme_v1
          yarn build
      - name: Verify source file
        run: |
          test -f plugins/gis-theme/adorsys_theme_v1/src/styles/main.scss 
